# Copyright 2023 CreuBlanca
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class MedicalDocumentReference(models.Model):

    _inherit = "medical.document.reference"

    autogenerated = fields.Boolean(default=False, readonly=True)
    document_type_id = fields.Many2one(auto_join=True)
    document_kind = fields.Selection(related="document_type_id.kind")
