from . import medical_encounter
from . import medical_request_group
from . import workflow_plan_definition
from . import queue_location_area
from . import queue_area
from . import res_partner
from . import res_partner_queue_location
from . import queue_token
from . import queue_token_location
