# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test Odoo

on:
    push:
        branches: ["13.0"]
    pull_request:
        branches: ["13.0"]

jobs:
    test:
        runs-on: ubuntu-latest
        container: ${{ matrix.container }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - container: ghcr.io/oca/oca-ci/py3.6-odoo13.0:latest
                    - container: ghcr.io/oca/oca-ci/py3.6-ocb13.0:latest
        env:
            WKHTMLTOPDF_VERSION: "0.12.5"
        services:
            postgres:
                image: postgres:9.6
                env:
                    POSTGRES_USER: odoo
                    POSTGRES_PASSWORD: odoo
                    POSTGRES_DB: odoo
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - run: apt update
            - run: pip install setuptools-odoo wheel
            - run:
                  apt install cups libcups2-dev libzbar-dev libxmlsec1-dev zip
                  libxmlsec1-openssl openssl mupdf-tools libmupdf-dev mupdf
                  poppler-utils -y
            - run: pip install pymupdf==1.16.18
            - run: pip install -r cb-requirements.txt
            - run:
                  pip install
                  git+https://github.com/tegin/cb-addons.git@13.0#subdirectory=setup
            - run: oca_install_addons
            - run: oca_init_test_database
            - name: licenses check
              run: manifestoo -d . check-licenses
            - name: development status check
              run: manifestoo -d . check-dev-status --default-dev-status=Beta
            - run: oca_run_tests
            - uses: codecov/codecov-action@v1
